### PR TITLE
Alert ingest

### PR DESCRIPTION
**Pull request by djperrefort**
This pull request transitions the project into using GCP based tools and introduces data ingestion into BigQuery.

Major changes include:
  - The `mock_stream` module has been replaced with the `ztf_archive module`. The two are essentially the same, except kafka streaming has been removed.
  - Logging is now performed using StackDriver
  - The ORM has been removed and data ingestion is now performed into the cloud with BigQuery. A new ORM or data interface will need to be created in another PR.
  - `broker.ztf_archive.iter_alerts` returns a list of alerts instead of individual alerts
  - A setup function is provided to set up a GCP project

Minor changes include:
  - Adds a setup.py file
  - Updated documentation and installation instructions
  - Moves some notes that were in the project README into the notes README

### CODE REVIEW

**Comment by troyraen** [comment]
Tried this on my Linux machine. When running `python setup.py install --user` I get warnings, but I think there are no errors (I can send you the output if that's helpful). 

However I get the following error when running `from broker.gcp_setup import setup_gcp`

> \>\>\> from broker.gcp_setup import setup_gcp
> Traceback (most recent call last):
>   File "\<stdin\>", line 1, in \<module\>
>   File "/home/tjr63/Documents/Pitt-Broker/broker/\_\_init\_\_.py", line 6, in <module>
>     from . import alert_ingestion, gcp_setup, ztf_archive
>   File "/home/tjr63/Documents/Pitt-Broker/broker/alert_ingestion/\_\_init\_\_.py", line 21, in <module>
>     from ._ingest_alerts import batch_ingest_alerts, stream_ingest_alerts
>   File "/home/tjr63/Documents/Pitt-Broker/broker/alert_ingestion/_ingest_alerts.py", line 12, in <module>
>     from google.cloud import bigquery, error_reporting, logging as gcp_logging
> ImportError: cannot import name 'error_reporting' from 'google.cloud' (/home/tjr63/.local/lib/python3.7/site-packages/google_cloud_core-0.29.1-py3.7.egg/google/cloud/\_\_init\_\_.py)

**Comment by djperrefort** [comment]
It looks like I left that dependency out of the requirements file by accident. Does the following fix it?

    pip install google-cloud-error-reporting

**Comment by troyraen** [comment]
Hmm, no, I get the same error. I'll try adding it to the requirements file and starting the process over.

**Comment by troyraen** [comment]
Ok, that seemed to work and now I get a different error in the same spot. Here's the error message:

```python
>>> from broker.gcp_setup import setup_gcp
WARNING: AstropyDeprecationWarning: astropy.extern.six will be removed in 4.0, use the six module directly if it is still needed [astropy.extern.six]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tjr63/Documents/Pitt-Broker/broker/__init__.py", line 6, in <module>
    from . import alert_ingestion, gcp_setup, ztf_archive
  File "/home/tjr63/Documents/Pitt-Broker/broker/alert_ingestion/__init__.py", line 21, in <module>
    from ._ingest_alerts import batch_ingest_alerts, stream_ingest_alerts
  File "/home/tjr63/Documents/Pitt-Broker/broker/alert_ingestion/_ingest_alerts.py", line 17, in <module>
    logging_client = gcp_logging.Client()
  File "/home/tjr63/.local/lib/python3.7/site-packages/google_cloud_logging-1.10.0-py3.7.egg/google/cloud/logging/client.py", line 105, in __init__
    project=project, credentials=credentials, _http=_http
  File "/home/tjr63/.local/lib/python3.7/site-packages/google_cloud_core-0.29.1-py3.7.egg/google/cloud/client.py", line 223, in __init__
    _ClientProjectMixin.__init__(self, project=project)
  File "/home/tjr63/.local/lib/python3.7/site-packages/google_cloud_core-0.29.1-py3.7.egg/google/cloud/client.py", line 175, in __init__
    project = self._determine_default(project)
  File "/home/tjr63/.local/lib/python3.7/site-packages/google_cloud_core-0.29.1-py3.7.egg/google/cloud/client.py", line 190, in _determine_default
    return _determine_default_project(project)
  File "/home/tjr63/.local/lib/python3.7/site-packages/google_cloud_core-0.29.1-py3.7.egg/google/cloud/_helpers.py", line 186, in _determine_default_project
    _, project = google.auth.default()
  File "/home/tjr63/.local/lib/python3.7/site-packages/google_auth-1.6.3-py3.7.egg/google/auth/_default.py", line 317, in default
    raise exceptions.DefaultCredentialsError(_HELP_MESSAGE)
google.auth.exceptions.DefaultCredentialsError: Could not automatically determine credentials. Please set GOOGLE_APPLICATION_CREDENTIALS or explicitly create credentials and re-run the application. For more information, please see https://cloud.google.com/docs/authentication/getting-started
```

I already setup a GCP project. If I follow the link at the end of the error message it wants me to setup a service account and set a `GOOGLE_APPLICATION_CREDENTIALS` environment variable... should I do that?

**Comment by djperrefort** [comment]
I had forgotten about this. Yes, you will need to set the environmental variable. You can do this in your global profile or in the conda environment as described in the README. Hopefully, that's the last missing step :+1:.

**Comment by troyraen** [comment]
That worked and I made it to `setup_gcp()` where I got this error:

```python
>>> setup_gcp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tjr63/.local/lib/python3.7/site-packages/pitt_broker-0.0.1-py3.7.egg/broker/gcp_setup.py", line 83, in setup_gcp
    _setup_logging_sinks()
  File "/home/tjr63/.local/lib/python3.7/site-packages/pitt_broker-0.0.1-py3.7.egg/broker/gcp_setup.py", line 53, in _setup_logging_sinks
    storage_client.get_bucket(logging_bucket_name)
  File "/home/tjr63/.local/lib/python3.7/site-packages/google_cloud_storage-1.15.0-py3.7.egg/google/cloud/storage/client.py", line 227, in get_bucket
    bucket.reload(client=self)
  File "/home/tjr63/.local/lib/python3.7/site-packages/google_cloud_storage-1.15.0-py3.7.egg/google/cloud/storage/_helpers.py", line 130, in reload
    _target_object=self,
  File "/home/tjr63/.local/lib/python3.7/site-packages/google_cloud_core-0.29.1-py3.7.egg/google/cloud/_http.py", line 319, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 GET https://www.googleapis.com/storage/v1/b/broker_logging_bucket?projection=noAcl: pbserviceaccount@pitt-broker.iam.gserviceaccount.com does not have storage.buckets.get access to broker_logging_bucket.
```

Is this something else I need to set up?

**Comment by djperrefort** [comment]
Can you check via the GCP console whether the bucket already exists?

**Comment by troyraen** [comment]
Looks like no, assuming I'm looking in the right place. I'll create one and try again.

**Comment by djperrefort** [comment]
When you downloaded the application credentials, what permission level did you set?

**Comment by troyraen** [comment]
For the 'Role' I selected Project -> Owner. I didn't see anything that specifically let me set a 'permission level'.

**Comment by djperrefort** [comment]
From the left menu bar select `IAM & Admin > IAM` and you should be able to set permission levels for your project.

**Comment by troyraen** [comment]
I see two members, me and the service account. Both are set to Role = Owner. What permissions should I be setting?

**Comment by troyraen** [comment]
I created a bucket for the project, but am getting the same error.

**Comment by troyraen** [comment]
I think maybe I don't have the right permissions to the bucket itself... trying to fix that now.

**Comment by troyraen** [comment]
Still not working, though there are so many roles I may not have selected the right ones.

The error message says 
`pbserviceaccount@pitt-broker.iam.gserviceaccount.com does not have storage.buckets.get access to broker_logging_bucket.`
Am I supposed to have a bucket called `broker_logging_bucket`?

**Comment by djperrefort** [comment]
The function should try to connect to a bucket called `broker_logging_bucket` and create it if it does not exist. The problem is that when `gcp_setup` tries to connect to the bucket it's told that it does not have the appropriate permissions. We can look through the GCP console together sometime tomorrow if you want and hopefully we can figure it out then.

**Comment by troyraen** [comment]
I see. Sounds good, thanks.

**Comment by djperrefort** [comment]
To document our offline conversation - The problem was that I didn't realize bucket names need to be unique across the GCP platform.

**Pull request merged**
